In [1]:
# import objects
import os
import pandas as pd
import numpy as np
import seaborn as sns; sns.set(style="ticks", color_codes=True)

from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [2]:
# read file
data_set = pd.read_csv('raw-responses-1.csv')
data_set = data_set.dropna()

In [3]:
# inspect data
type(data_set)
data_set.head()
data_set.describe()
data_set.dtypes
print(data_set.shape)
data_set.info() #count non-null values in the columns
data_set.isnull().sum(axis=0) #count blanks in the columns

(1586, 65)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1586 entries, 0 to 1614
Data columns (total 65 columns):
q0001          1586 non-null object
q0002          1586 non-null object
q0004_0001     1586 non-null object
q0004_0002     1586 non-null object
q0004_0003     1586 non-null object
q0004_0004     1586 non-null object
q0004_0005     1586 non-null object
q0004_0006     1586 non-null object
q0005          1586 non-null object
q0007_0001     1586 non-null object
q0007_0002     1586 non-null object
q0007_0003     1586 non-null object
q0007_0004     1586 non-null object
q0007_0005     1586 non-null object
q0007_0006     1586 non-null object
q0007_0007     1586 non-null object
q0007_0008     1586 non-null object
q0007_0009     1586 non-null object
q0007_0010     1586 non-null object
q0007_0011     1586 non-null object
q0008_0001     1586 non-null object
q0008_0002     1586 non-null object
q0008_0003     1586 non-null object
q0008_0004     1586 non-null object
q0008_0005     158

q0001          0
q0002          0
q0004_0001     0
q0004_0002     0
q0004_0003     0
q0004_0004     0
q0004_0005     0
q0004_0006     0
q0005          0
q0007_0001     0
q0007_0002     0
q0007_0003     0
q0007_0004     0
q0007_0005     0
q0007_0006     0
q0007_0007     0
q0007_0008     0
q0007_0009     0
q0007_0010     0
q0007_0011     0
q0008_0001     0
q0008_0002     0
q0008_0003     0
q0008_0004     0
q0008_0005     0
q0008_0006     0
q0008_0007     0
q0008_0008     0
q0008_0009     0
q0008_0010     0
              ..
q0020_0001     0
q0020_0002     0
q0020_0003     0
q0020_0004     0
q0020_0005     0
q0020_0006     0
q0021_0001     0
q0021_0002     0
q0021_0003     0
q0021_0004     0
q0022          0
q0024          0
q0025_0001     0
q0025_0002     0
q0025_0003     0
q0026          0
q0028          0
q0029          0
q0030          0
q0034          0
q0035          0
q0036          0
race2          0
racethn4       0
educ3          0
educ4          0
age3           0
kids          

In [4]:
# subset with necessary columns only
columns_or = ['q0001','q0002','q0005','q0008_0001','q0008_0002','q0008_0003','q0008_0004','q0008_0005'
              ,'q0008_0006','q0008_0007','q0008_0008','q0008_0009','q0008_0010','q0008_0011','q0008_0012'
              ,'q0017','q0018','q0022','q0024','q0026','age3','q0028','q0029' ]

columns_cat = ['q0001_cat','q0002_cat','q0005_cat','q0008_0001_cat','q0008_0002_cat','q0008_0003_cat'
               ,'q0008_0004_cat','q0008_0005_cat','q0008_0006_cat','q0008_0007_cat','q0008_0008_cat'
               ,'q0008_0009_cat','q0008_0010_cat','q0008_0011_cat','q0008_0012_cat','q0017_cat','q0018_cat'
               ,'q0022_cat','q0024_cat','q0026_cat','age3_cat','q0028_cat','q0029_cat']


data_sub = data_set[columns_or]

In [5]:
# verify data
data_sub.dtypes
data_sub.info() #count non-null values in the columns
data_sub.isnull().sum(axis=0) #count blanks in the columns

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1586 entries, 0 to 1614
Data columns (total 23 columns):
q0001         1586 non-null object
q0002         1586 non-null object
q0005         1586 non-null object
q0008_0001    1586 non-null object
q0008_0002    1586 non-null object
q0008_0003    1586 non-null object
q0008_0004    1586 non-null object
q0008_0005    1586 non-null object
q0008_0006    1586 non-null object
q0008_0007    1586 non-null object
q0008_0008    1586 non-null object
q0008_0009    1586 non-null object
q0008_0010    1586 non-null object
q0008_0011    1586 non-null object
q0008_0012    1586 non-null object
q0017         1586 non-null object
q0018         1586 non-null object
q0022         1586 non-null object
q0024         1586 non-null object
q0026         1586 non-null object
age3          1586 non-null object
q0028         1586 non-null object
q0029         1586 non-null object
dtypes: object(23)
memory usage: 154.9+ KB


q0001         0
q0002         0
q0005         0
q0008_0001    0
q0008_0002    0
q0008_0003    0
q0008_0004    0
q0008_0005    0
q0008_0006    0
q0008_0007    0
q0008_0008    0
q0008_0009    0
q0008_0010    0
q0008_0011    0
q0008_0012    0
q0017         0
q0018         0
q0022         0
q0024         0
q0026         0
age3          0
q0028         0
q0029         0
dtype: int64

In [6]:
# categorical encoding (text data into numerical)
obj_df = data_sub

# change all columns to 'category' type to apply categorical transformation
for col in [columns_or]:
    obj_df[col] = obj_df[col].astype('category')

C:\Users\pdona\Anaconda3\lib\site-packages\pandas\core\frame.py:3140: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]


In [8]:
# creating categorical columns based in each df column
obj_df['q0001_cat'] = obj_df['q0001'].cat.codes
obj_df['q0002_cat'] = obj_df['q0002'].cat.codes
obj_df['q0005_cat'] = obj_df['q0005'].cat.codes
obj_df['q0008_0001_cat'] = obj_df['q0008_0001'].cat.codes
obj_df['q0008_0002_cat'] = obj_df['q0008_0002'].cat.codes
obj_df['q0008_0003_cat'] = obj_df['q0008_0003'].cat.codes
obj_df['q0008_0004_cat'] = obj_df['q0008_0004'].cat.codes
obj_df['q0008_0005_cat'] = obj_df['q0008_0005'].cat.codes
obj_df['q0008_0006_cat'] = obj_df['q0008_0006'].cat.codes
obj_df['q0008_0007_cat'] = obj_df['q0008_0007'].cat.codes
obj_df['q0008_0008_cat'] = obj_df['q0008_0008'].cat.codes
obj_df['q0008_0009_cat'] = obj_df['q0008_0009'].cat.codes
obj_df['q0008_0010_cat'] = obj_df['q0008_0010'].cat.codes
obj_df['q0008_0011_cat'] = obj_df['q0008_0011'].cat.codes
obj_df['q0008_0012_cat'] = obj_df['q0008_0012'].cat.codes
obj_df['q0017_cat'] = obj_df['q0017'].cat.codes
obj_df['q0018_cat'] = obj_df['q0018'].cat.codes
obj_df['q0022_cat'] = obj_df['q0022'].cat.codes
obj_df['q0024_cat'] = obj_df['q0024'].cat.codes
obj_df['q0026_cat'] = obj_df['q0026'].cat.codes
obj_df['age3_cat'] = obj_df['age3'].cat.codes
obj_df['q0028_cat'] = obj_df['q0028'].cat.codes
obj_df['q0029_cat'] = obj_df['q0029'].cat.codes

C:\Users\pdona\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\pdona\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\pdona\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in t

In [9]:
# creating new df excluding original columns
df_cat = obj_df.drop(['q0001','q0002','q0005','q0008_0001','q0008_0002','q0008_0003','q0008_0004','q0008_0005'
              ,'q0008_0006','q0008_0007','q0008_0008','q0008_0009','q0008_0010','q0008_0011','q0008_0012'
              ,'q0017','q0018','q0022','q0024','q0026','age3','q0028','q0029'], axis=1)


In [10]:
# Gaussian Naive Bayes Classification

In [12]:
# creating 'x' and 'y' objects to be used into the Multiple Linear Regression
x = pd.DataFrame(df_cat, columns=['q0002_cat','q0005_cat','q0008_0001_cat','q0008_0002_cat','q0008_0003_cat'
               ,'q0008_0004_cat','q0008_0005_cat','q0008_0006_cat','q0008_0007_cat','q0008_0008_cat'
               ,'q0008_0009_cat','q0008_0010_cat','q0008_0011_cat','q0008_0012_cat','q0017_cat','q0018_cat'
               ,'q0022_cat','q0024_cat','q0026_cat','age3_cat','q0028_cat','q0029_cat'])

y = pd.DataFrame(df_cat, columns=['q0001_cat'])


In [13]:
# feature extraction
np.set_printoptions(suppress=True)

test = SelectKBest(score_func=chi2, k=3)
fit = test.fit(x, y)

In [14]:
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)

[43.464 23.407  4.023 11.993 19.044 13.7    1.813  5.18  20.796 21.17
  7.242  3.732  1.19   3.774 10.8   80.027  6.009  3.301  7.886  2.077
  1.92   4.463]


In [15]:
# recriating x with better scored features
x = pd.DataFrame(df_cat, columns=['q0008_0001_cat','q0029_cat','q0008_0006_cat','q0022_cat','q0008_0009_cat'
                                  ,'q0026_cat','q0017_cat','q0008_0002_cat','q0008_0004_cat','q0008_0003_cat'
                                  ,'q0008_0007_cat','q0008_0008_cat','q0005_cat','q0002_cat','q0018_cat'])


In [17]:
# spliting database
k2 = int(len(df_cat['q0001_cat']) * 0.2) # 20% samples

x_train = x[k2:] #80%
x_train = np.c_[np.ones(len(x_train),dtype='int64'),x_train]
y_train = y[k2:]

x_test = x[:k2] #20%
x_test = np.c_[np.ones(len(x_test),dtype='int64'),x_test]
y_test = y[:k2]
y_test = y_test.round(0)

In [18]:
# train the model
clf = GaussianNB()
clf.fit(x_train, y_train)


C:\Users\pdona\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [22]:
# use the model to predict the labels of the test data
predicted = clf.predict(x_test)
expected = y_test

predicted_df = pd.DataFrame({'q0001_cat':predicted})

predicted_m = predicted_df.values
exprected_m = expected.values

In [23]:
# check performance 
matches = (predicted_m == exprected_m)
correct = (matches.sum() / float(len(matches)))*100
print('Coredictions match(%): ',correct.round(2))

print(metrics.confusion_matrix(exprected_m, predicted_m))

Coredictions match(%):  16.09
[[  1   0   0   0   0]
 [  5   0   0   3   0]
 [ 19   0   4  10   0]
 [104   0   6  39   8]
 [ 93   0   3  15   7]]
